/** Generated file, modifications will be overwritten! **/
search.addDoc("### Coding","","link");
search.addDoc("### Math","","link");
search.addDoc("### Other","","link");
search.addDoc("### Other","","link");
search.addDoc("### Personal","","link");
search.addDoc("### Powdrsoft","","link");
search.addDoc("### Surf","","link");
search.addDoc("[Find My Device](https://www.google.com/android/find/)","","link");
search.addDoc("[Find Your Phone](https://myaccount.google.com/u/1/find-your-phone)","","link");
search.addDoc("[Google Codelabs](https://codelabs.developers.google.com/)","","link");
search.addDoc("[Kustväder Limhamn](https://www.kustvader.se/malm%C3%B6-limhamn)","","link");
search.addDoc("[Lomma windsurfing](https://lommavindsurfing.se/)","","link");
search.addDoc("[Småbåtshamnen Limhamn](https://www.weatherlink.com/embeddablePage/show/57ea9ac7cfe540c3a21e2aa23a2f1e53/summary)","","link");
search.addDoc("[Småbåtshamnen](https://www.weatherlink.com/embeddablePage/show/57ea9ac7cfe540c3a21e2aa23a2f1e53/summary)","","link");
search.addDoc("[Wikipedia](https://www.wikipedia.org/)","","link");
search.addDoc("[WolframAlpha](http://www.wolframalpha.com/)","","link");
search.addDoc("[barnkanalen](https://www.svt.se/barnkanalen/)","","link");
search.addDoc("[cineasterna](https://www.cineasterna.com/sv/)","","link");
search.addDoc("[coolcompany.com](https://coolcompany.com/se/)","","link");
search.addDoc("[dmi forecast Lomma](http://www.dmi.dk/vejr/til-lands/byvejr/by/vis/SE/2694264/Lomma,Sverige)","","link");
search.addDoc("[findwind](https://findwind.se/wind?sl=f)","","link");
search.addDoc("[fredrik.rambris.com](https://fredrik.rambris.com/)","","link");
search.addDoc("[gmail](https://mail.google.com/)","","link");
search.addDoc("[kite.se](https://www.kite.se/spotsvader)","","link");
search.addDoc("[kustväder](https://www.kustvader.se/malm%C3%B6-limhamn)","","link");
search.addDoc("[lön som konsult](https://www.cinode.com/blogg/konsult/lon-konsult-sa-mycket-bor-du-tjana/)","","link");
search.addDoc("[maps](https://www.google.com/maps)","","link");
search.addDoc("[marcopeg.com](https://marcopeg.com)","","link");
search.addDoc("[messages](https://messages.google.com/web/conversations)","","link");
search.addDoc("[photos](https://photos.google.com/)","","link");
search.addDoc("[spotify](https://www.spotify.com/se/)","","link");
search.addDoc("[svtplay](https://www.svtplay.se/)","","link");
search.addDoc("[ted](https://www.ted.com/)","","link");
search.addDoc("[windguru Lomma](https://www.windguru.cz/47956)","","link");
search.addDoc("[www.driva-eget.se lonekalkyl](https://www.driva-eget.se/kalkyler/lonekalkyl)","","link");
search.addDoc("[youtube](https://www.youtube.com/)","","link");
search.addDoc("[youtube](https://www.youtube.com/)","","link");
search.addDoc("http://peopleintech.se/konsult/","","link");
search.addDoc("http://t.ericsson.gitlab.io","","link");
search.addDoc("http://tericsson.appspot.com","","link");
search.addDoc("http://tibbe.gitlab.io","","link");
search.addDoc("http://www.kompetensgruppen.se/natverk/konsultnatverket/","","link");
search.addDoc("http://www.nomachetejuggling.com","","link");
search.addDoc("http://www.zelago.se/konsultnatverk.html","","link");
search.addDoc("https://adventofcode.com","","link");
search.addDoc("https://aws.amazon.com/lambda/pricing/","","link");
search.addDoc("https://brainping.com/","","link");
search.addDoc("https://civilekonomerna.se/rad-stod/hur-mycket-ska-jag-ta-betalt-en-guide-till-dig-med-eget-foretag","","link");
search.addDoc("https://cloud.google.com/functions/pricing","","link");
search.addDoc("https://dagens.site","","link");
search.addDoc("https://exercism.io","","link");
search.addDoc("https://housing.powdrsoft.com","","link");
search.addDoc("https://keep.consulting/","","link");
search.addDoc("https://konsult.coop/members","","link");
search.addDoc("https://leetcode.com/problemset","","link");
search.addDoc("https://ncase.me","","link");
search.addDoc("https://nordic.businessinsider.com/malmos-tech-scene-is-boiling-hot---here-are-7-startups-shaking-up-old-school-industries-out-of-minc-incubator-2017-7","","link");
search.addDoc("https://powdrsoft.com","","link");
search.addDoc("https://riktiga.com/","","link");
search.addDoc("https://scratch.mit.edu","","link");
search.addDoc("https://tionit.blogspot.se","","link");
search.addDoc("https://tobias-ericsson-sw-development.blogspot.se","","link");
search.addDoc("https://tobias-ericsson.appspot.com","","link");
search.addDoc("https://tobias-ericsson.github.io","","link");
search.addDoc("https://tobias.ericsson.gitlab.io","","link");
search.addDoc("https://tobiasericsson.blogspot.se","","link");
search.addDoc("https://www.asociety.se/konsult/varfor","","link");
search.addDoc("https://www.cloudflare.com/plans/","","link");
search.addDoc("https://www.enmanskonsulterna.se/bli-egen-konsult","","link");
search.addDoc("https://www.eworkgroup.com/se/konsult","","link");
search.addDoc("https://www.hackerrank.com/dashboard","","link");
search.addDoc("https://www.hanselman.com/blog/","","link");
search.addDoc("https://www.heroku.com/pricing","","link");
search.addDoc("https://www.konsulter.net/bli-konsult/","","link");
search.addDoc("https://www.kvadrat.se/bli-kvadratare/","","link");
search.addDoc("https://www.openshift.com/products/online/","","link");
search.addDoc("https://www.trovisio.com/sv/consultants","","link");
