/** Generated file, modifications will be overwritten! **/
search.addDoc("http://www.nomachetejuggling.com","","link");
search.addDoc("https://www.hanselman.com/blog/","","link");
search.addDoc("https://www.cloudflare.com/plans/","","link");
search.addDoc("https://www.heroku.com/pricing","","link");
search.addDoc("https://www.openshift.com/products/online/","","link");
search.addDoc("https://cloud.google.com/functions/pricing","","link");
search.addDoc("https://aws.amazon.com/lambda/pricing/","","link");
search.addDoc("[sebastiandahlgren.se](http://sebastiandahlgren.se)","","link");
search.addDoc("[fredrik.rambris.com](https://fredrik.rambris.com/)","","link");
search.addDoc("[coolcompany.com](https://coolcompany.com/se/)","","link");
search.addDoc("[www.driva-eget.se lonekalkyl](https://www.driva-eget.se/kalkyler/lonekalkyl)","","link");
search.addDoc("[lön som konsult](https://www.cinode.com/blogg/konsult/lon-konsult-sa-mycket-bor-du-tjana/)","","link");
search.addDoc("https://civilekonomerna.se/rad-stod/hur-mycket-ska-jag-ta-betalt-en-guide-till-dig-med-eget-foretag","","link");
search.addDoc("https://nordic.businessinsider.com/malmos-tech-scene-is-boiling-hot---here-are-7-startups-shaking-up-old-school-industries-out-of-minc-incubator-2017-7","","link");
search.addDoc("www.eworkgroup.com/se/konsult","","link");
search.addDoc("https://www.konsulter.net/bli-konsult/","","link");
search.addDoc("https://konsult.coop/members","","link");
search.addDoc("https://www.enmanskonsulterna.se/bli-egen-konsult","","link");
search.addDoc("http://peopleintech.se/konsult/","","link");
search.addDoc("http://www.zelago.se/konsultnatverk.html","","link");
search.addDoc("https://www.kvadrat.se/bli-kvadratare/","","link");
search.addDoc("http://www.kompetensgruppen.se/natverk/konsultnatverket/","","link");
search.addDoc("https://www.asociety.se/konsult/varfor","","link");
search.addDoc("https://brainping.com/","","link");
search.addDoc("https://www.trovisio.com/sv/consultants","","link");
search.addDoc("[gmail](https://mail.google.com/)","","link");
search.addDoc("[messages](https://messages.android.com/)","","link");
search.addDoc("[maps](https://www.google.com/maps)","","link");
search.addDoc("[youtube](https://www.youtube.com/)","","link");
search.addDoc("[WolframAlpha](http://www.wolframalpha.com/)","","link");
search.addDoc("[Wikipedia](https://www.wikipedia.org/)","","link");
search.addDoc("[Google Codelabs](https://codelabs.developers.google.com/)","","link");
search.addDoc("https://ncase.me/","","link");
search.addDoc("[spotify](https://www.spotify.com/se/)","","link");
search.addDoc("[current sea weather around Malmö](seawind.html)","","link");
search.addDoc("[dmi forecast Lomma](http://www.dmi.dk/vejr/til-lands/byvejr/by/vis/SE/2694264/Lomma,Sverige)","","link");
search.addDoc("[Lomma windsurfing](http://lommavindsurfing.se/vader/)","","link");
search.addDoc("[kite.se](https://kite.se/v2/skane/)","","link");
search.addDoc("[windguru Lomma](https://www.windguru.cz/47956)","","link");
search.addDoc("https://tibbes.com","","link");
search.addDoc("https://news.tibbes.com","","link");
search.addDoc("https://week.tibbes.com","","link");
search.addDoc("http://tericsson.appspot.com","","link");
search.addDoc("https://tobias-ericsson.appspot.com","","link");
search.addDoc("https://tobiasericsson.blogspot.se","","link");
search.addDoc("https://tobias-ericsson-sw-development.blogspot.se","","link");
search.addDoc("https://tionit.blogspot.se","","link");
search.addDoc("http://tibbe.gitlab.io","","link");
search.addDoc("http://t.ericsson.gitlab.io","","link");
search.addDoc("https://tobias-ericsson.github.io","","link");
search.addDoc("[ted](https://www.ted.com/)","","link");
search.addDoc("[svtplay](https://www.svtplay.se/)","","link");
search.addDoc("[barnkanalen](https://www.svt.se/barnkanalen/)","","link");
search.addDoc("[youtube](https://www.youtube.com/)","","link");
search.addDoc("[cineasterna](https://www.cineasterna.com/sv/)","","link");
search.addDoc("[courel.se](http://courel.se/)","","link");
search.addDoc("[find your phone](https://myaccount.google.com/u/1/find-your-phone)","","link");
search.addDoc("https://scratch.mit.edu/","","link");
